# ==========================================
# WellHub / MyTool-V2 — Coolify Production Build
# ==========================================
# Vite inlines import.meta.env.VITE_* at BUILD TIME.
# All VITE_ variables must be passed as ARG to the builder stage.
#
# Required in Coolify:
#   VITE_APPWRITE_ENDPOINT, VITE_APPWRITE_PROJECT_ID, VITE_APPWRITE_DATABASE_ID
# Optional (have code fallbacks):
#   VITE_COLLECTION_* variables
# ==========================================

# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

# ── Build Args for Vite env variables ─────────────────────────────────
ARG VITE_APPWRITE_ENDPOINT
ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_DATABASE_ID
ARG VITE_COLLECTION_USERS_PROFILE
ARG VITE_COLLECTION_FAMILIES
ARG VITE_COLLECTION_FAMILY_MEMBERS
ARG VITE_COLLECTION_EVENTS
ARG VITE_COLLECTION_CHORES
ARG VITE_COLLECTION_BUDGET_ENTRIES
ARG VITE_COLLECTION_ALCOHOL_LOGS
ARG VITE_COLLECTION_DRINKS
ARG VITE_COLLECTION_GOALS
ARG VITE_COLLECTION_USER_PROFILES
ARG VITE_COLLECTION_CIRCLE_INVITATIONS
ARG VITE_COLLECTION_CIRCLE_MEMBERS
ARG VITE_COLLECTION_CIRCLE_ALERTS
ARG VITE_COLLECTION_CIRCLE_EMERGENCY
ARG VITE_COLLECTION_LIVE_SESSIONS
ARG VITE_COLLECTION_SAFETY_EVENTS
ARG VITE_COLLECTION_EMERGENCY_ALERTS

ENV VITE_APPWRITE_ENDPOINT=$VITE_APPWRITE_ENDPOINT
ENV VITE_APPWRITE_PROJECT_ID=$VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_DATABASE_ID=$VITE_APPWRITE_DATABASE_ID
ENV VITE_COLLECTION_USERS_PROFILE=$VITE_COLLECTION_USERS_PROFILE
ENV VITE_COLLECTION_FAMILIES=$VITE_COLLECTION_FAMILIES
ENV VITE_COLLECTION_FAMILY_MEMBERS=$VITE_COLLECTION_FAMILY_MEMBERS
ENV VITE_COLLECTION_EVENTS=$VITE_COLLECTION_EVENTS
ENV VITE_COLLECTION_CHORES=$VITE_COLLECTION_CHORES
ENV VITE_COLLECTION_BUDGET_ENTRIES=$VITE_COLLECTION_BUDGET_ENTRIES
ENV VITE_COLLECTION_ALCOHOL_LOGS=$VITE_COLLECTION_ALCOHOL_LOGS
ENV VITE_COLLECTION_DRINKS=$VITE_COLLECTION_DRINKS
ENV VITE_COLLECTION_GOALS=$VITE_COLLECTION_GOALS
ENV VITE_COLLECTION_USER_PROFILES=$VITE_COLLECTION_USER_PROFILES
ENV VITE_COLLECTION_CIRCLE_INVITATIONS=$VITE_COLLECTION_CIRCLE_INVITATIONS
ENV VITE_COLLECTION_CIRCLE_MEMBERS=$VITE_COLLECTION_CIRCLE_MEMBERS
ENV VITE_COLLECTION_CIRCLE_ALERTS=$VITE_COLLECTION_CIRCLE_ALERTS
ENV VITE_COLLECTION_CIRCLE_EMERGENCY=$VITE_COLLECTION_CIRCLE_EMERGENCY
ENV VITE_COLLECTION_LIVE_SESSIONS=$VITE_COLLECTION_LIVE_SESSIONS
ENV VITE_COLLECTION_SAFETY_EVENTS=$VITE_COLLECTION_SAFETY_EVENTS
ENV VITE_COLLECTION_EMERGENCY_ALERTS=$VITE_COLLECTION_EMERGENCY_ALERTS

COPY . .
RUN npm run build

# Stage 2: Production server
FROM nginx:alpine AS runner

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:80/ || exit 1

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]